name: Build and deploy Python FastAPI app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

# 同時実行を制限して競合を防止
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'              # Python のバージョンを設定
  APP_NAME: tech0-gen-8-step4-dtx-poback  # App Service の名前

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Prepare deployment package
        run: |
          mkdir -p deployment_package
          cp -r *.py deployment_package/
          cp requirements.txt deployment_package/
          
          # 必要なディレクトリがあれば追加
          if [ -d "templates" ]; then
            cp -r templates deployment_package/
          fi
          if [ -d "static" ]; then
            cp -r static deployment_package/
          fi
          
          # .env.example があれば .env としてコピー
          if [ -f ".env.example" ]; then
            cp .env.example deployment_package/.env
          fi
          
          # デプロイパッケージの内容を確認
          echo "Deployment package contents:"
          ls -la deployment_package/
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: deployment_package/
          retention-days: 1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      
      - name: Display deployment contents
        run: |
          echo "Deployment contents:"
          ls -la
          
          # requirements.txt の内容確認
          echo "requirements.txt contents:"
          cat requirements.txt
      
      - name: Deploy to Azure Web App with cleanup
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          clean: true    # 既存のファイルをクリーンアップして競合を防止
          restart: true  # デプロイ後に再起動
